# Generated by Django 4.0.3 on 2022-06-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('question_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('pack_name', models.TextField()),
                ('question_id', models.TextField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_image', models.BooleanField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%M/%D/')),
                ('answer', models.TextField()),
                ('pack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_packages.questionpackage')),
            ],
        ),
    ]
