# Generated by Django 4.0.3 on 2022-06-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%M/%D/'),
        ),
    ]
